config:
  selfUrl: # https://saas.abp_ms_test.dev
  corsOrigins: https://abp_ms_test-st-gateway-web,https://abp_ms_test-st-gateway-public-web
  connectionStrings:
    administrationService: #
    saasService: #
  authServer:
    authority: # http://abp_ms_test-st-authserver
    requireHttpsMetadata: # "false"
    metadataAddress: # https://authserver.abp_ms_test.dev/.well-known/openid-configuration
    swaggerClientId: WebGateway_Swagger
  dotnetEnv: Staging
  redisHost: #
  rabbitmqHost: #
  elasticsearchUrl: #
  stringEncryptionDefaultPassPhrase: gsKnGZ041HLL4IM8
  AbpLicenseCode: #

ingress:
  host: saas.abp_ms_test.dev
  tlsSecret: abp_ms_test-tls

image:
  repository: mycompanyname/abp_ms_test-service-saas
  tag: latest
  pullPolicy: IfNotPresent

env: {}      